### ISSUE TITLE
WebSocket server crash / error

### ISSUE THREAD

**Issue by tompointexe** [Er1807/VRCWS#5]
Hi, i'm getting an error when the sevrer in his docker container tryes to connect to redis from what i see

```
Connection to Redis established
Unhandled exception. Unhandled exception. StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SETEX Exception:63779762294:Message; UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.50.36290, mc: 1/1/0, mgr: 10 of 10 available, clientName: a2ebe09bc72d, IOCP: (Busy=0,Free=1000,Min=250,Max=1000), WORKER: (Busy=2,Free=32765,Min=250,Max=32767), v: 2.2.50.36290
 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.50.36290
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2840
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2535
   at Server.Redis.LogError(Exception exception, Message message, String userID, String world) in /app/Redis.cs:line 79
   at Server.VRCWS.OnMessage(MessageEventArgs e) in /app/Program.cs:line 215
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SETEX Exception:63779762294:Message; UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.50.36290, mc: 1/1/0, mgr: 10 of 10 available, clientName: a2ebe09bc72d, IOCP: (Busy=0,Free=1000,Min=250,Max=1000), WORKER: (Busy=4,Free=32763,Min=250,Max=32767), v: 2.2.50.36290
 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.50.36290
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2840
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2535
   at Server.Redis.LogError(Exception exception, Message message, String userID, String world) in /app/Redis.cs:line 79
   at Server.VRCWS.OnMessage(MessageEventArgs e) in /app/Program.cs:line 215
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
This happens on a new docker install of the server container
Thanks for looking into it

**Comment by Er1807** [comment]
Hi, sorry forgot to indluse the docker-compose file. It creates its own redis server. Jere is my current one but im gonna upload a cleaner version later
```
version: '3'
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '10.100.100.1:6379:6379'
    networks:
      - proxy
    volumes:
      - ./data:/data
  vrcws:
    image: er1807/vrcws:latest
    restart: unless-stopped
    environment:
      REDIS: 'redis:6379'
    depends_on:
      - "redis"
    user: "${SUID}:${SGID}"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vrcws.rule=Host(`vrcws.er1807.de`)
      - traefik.http.routers.vrcws.tls=true
      - traefik.http.routers.vrcws.tls.certresolver=letsEncryptProd
      - traefik.http.routers.vrcws.service=vrcws
      - traefik.http.services.vrcws.loadbalancer.server.port=8080
networks:
  proxy:
    external: true
```

**Comment by tompointexe** [comment]
Awsome thanks !! i'm gonna try to make it work, else i'l wait for you to update the docker image :)

**Comment by tompointexe** [comment]
sadly still crashing with the same error message, i'l wait for you to push an update and try again :)

**Comment by Er1807** [comment]
Hi, finally had some time to clean it up. This should work in any enviroment
https://github.com/Er1807/VRCWS/blob/main/Server/docker-compose.yml

**Comment by tompointexe** [comment]
Awsome it works !! Thanks a lot !!
